/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnShowsRouteImport } from './routes/en.shows'
import { Route as RuShowsRouteImport } from './routes/ru.shows'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminLitterRouteImport } from './routes/_authenticated/admin.litter'
import { Route as AuthenticatedAdminPhotosRouteImport } from './routes/_authenticated/admin.photos'
import { Route as AuthenticatedAdminShowsRouteImport } from './routes/_authenticated/admin.shows'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as EnLegalOfferRouteImport } from './routes/en.legal.offer'
import { Route as EnLegalPrivacyRouteImport } from './routes/en.legal.privacy'
import { Route as EnLegalTermsRouteImport } from './routes/en.legal.terms'
import { Route as RuLegalOfferRouteImport } from './routes/ru.legal.offer'
import { Route as RuLegalPrivacyRouteImport } from './routes/ru.legal.privacy'
import { Route as RuLegalTermsRouteImport } from './routes/ru.legal.terms'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnShowsRoute = EnShowsRouteImport.update({
  id: '/en/shows',
  path: '/en/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const RuShowsRoute = RuShowsRouteImport.update({
  id: '/ru/shows',
  path: '/ru/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLitterRoute =
  AuthenticatedAdminLitterRouteImport.update({
    id: '/litter',
    path: '/litter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPhotosRoute =
  AuthenticatedAdminPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShowsRoute = AuthenticatedAdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const EnLegalOfferRoute = EnLegalOfferRouteImport.update({
  id: '/en/legal/offer',
  path: '/en/legal/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLegalPrivacyRoute = EnLegalPrivacyRouteImport.update({
  id: '/en/legal/privacy',
  path: '/en/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLegalTermsRoute = EnLegalTermsRouteImport.update({
  id: '/en/legal/terms',
  path: '/en/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLegalOfferRoute = RuLegalOfferRouteImport.update({
  id: '/ru/legal/offer',
  path: '/ru/legal/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLegalPrivacyRoute = RuLegalPrivacyRouteImport.update({
  id: '/ru/legal/privacy',
  path: '/ru/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLegalTermsRoute = RuLegalTermsRouteImport.update({
  id: '/ru/legal/terms',
  path: '/ru/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/shows': typeof EnShowsRoute
  '/ru/shows': typeof RuShowsRoute
  '/en/': typeof EnIndexRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/litter': typeof AuthenticatedAdminLitterRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/en/shows': typeof EnShowsRoute
  '/ru/shows': typeof RuShowsRoute
  '/en': typeof EnIndexRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/litter': typeof AuthenticatedAdminLitterRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/shows': typeof EnShowsRoute
  '/ru/shows': typeof RuShowsRoute
  '/en/': typeof EnIndexRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/litter': typeof AuthenticatedAdminLitterRoute
  '/_authenticated/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/_authenticated/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/en/shows'
    | '/ru/shows'
    | '/en/'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/finance'
    | '/admin/litter'
    | '/admin/photos'
    | '/admin/shows'
    | '/admin/tickets'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/en/shows'
    | '/ru/shows'
    | '/en'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/finance'
    | '/admin/litter'
    | '/admin/photos'
    | '/admin/shows'
    | '/admin/tickets'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/en/shows'
    | '/ru/shows'
    | '/en/'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/litter'
    | '/_authenticated/admin/photos'
    | '/_authenticated/admin/shows'
    | '/_authenticated/admin/tickets'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/_authenticated/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnShowsRoute: typeof EnShowsRoute
  RuShowsRoute: typeof RuShowsRoute
  EnIndexRoute: typeof EnIndexRoute
  EnLegalOfferRoute: typeof EnLegalOfferRoute
  EnLegalPrivacyRoute: typeof EnLegalPrivacyRoute
  EnLegalTermsRoute: typeof EnLegalTermsRoute
  RuLegalOfferRoute: typeof RuLegalOfferRoute
  RuLegalPrivacyRoute: typeof RuLegalPrivacyRoute
  RuLegalTermsRoute: typeof RuLegalTermsRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/shows': {
      id: '/en/shows'
      path: '/en/shows'
      fullPath: '/en/shows'
      preLoaderRoute: typeof EnShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/shows': {
      id: '/ru/shows'
      path: '/ru/shows'
      fullPath: '/ru/shows'
      preLoaderRoute: typeof RuShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/litter': {
      id: '/_authenticated/admin/litter'
      path: '/litter'
      fullPath: '/admin/litter'
      preLoaderRoute: typeof AuthenticatedAdminLitterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/photos': {
      id: '/_authenticated/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AuthenticatedAdminPhotosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shows': {
      id: '/_authenticated/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AuthenticatedAdminShowsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/en/legal/offer': {
      id: '/en/legal/offer'
      path: '/en/legal/offer'
      fullPath: '/en/legal/offer'
      preLoaderRoute: typeof EnLegalOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal/privacy': {
      id: '/en/legal/privacy'
      path: '/en/legal/privacy'
      fullPath: '/en/legal/privacy'
      preLoaderRoute: typeof EnLegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal/terms': {
      id: '/en/legal/terms'
      path: '/en/legal/terms'
      fullPath: '/en/legal/terms'
      preLoaderRoute: typeof EnLegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/legal/offer': {
      id: '/ru/legal/offer'
      path: '/ru/legal/offer'
      fullPath: '/ru/legal/offer'
      preLoaderRoute: typeof RuLegalOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/legal/privacy': {
      id: '/ru/legal/privacy'
      path: '/ru/legal/privacy'
      fullPath: '/ru/legal/privacy'
      preLoaderRoute: typeof RuLegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/legal/terms': {
      id: '/ru/legal/terms'
      path: '/ru/legal/terms'
      fullPath: '/ru/legal/terms'
      preLoaderRoute: typeof RuLegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminLitterRoute: typeof AuthenticatedAdminLitterRoute
  AuthenticatedAdminPhotosRoute: typeof AuthenticatedAdminPhotosRoute
  AuthenticatedAdminShowsRoute: typeof AuthenticatedAdminShowsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminLitterRoute: AuthenticatedAdminLitterRoute,
  AuthenticatedAdminPhotosRoute: AuthenticatedAdminPhotosRoute,
  AuthenticatedAdminShowsRoute: AuthenticatedAdminShowsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EnShowsRoute: EnShowsRoute,
  RuShowsRoute: RuShowsRoute,
  EnIndexRoute: EnIndexRoute,
  EnLegalOfferRoute: EnLegalOfferRoute,
  EnLegalPrivacyRoute: EnLegalPrivacyRoute,
  EnLegalTermsRoute: EnLegalTermsRoute,
  RuLegalOfferRoute: RuLegalOfferRoute,
  RuLegalPrivacyRoute: RuLegalPrivacyRoute,
  RuLegalTermsRoute: RuLegalTermsRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
