/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminShowsRouteImport } from './routes/_authenticated/admin.shows'
import { Route as EnLegalOfferRouteImport } from './routes/en.legal.offer'
import { Route as EnLegalPrivacyRouteImport } from './routes/en.legal.privacy'
import { Route as EnLegalTermsRouteImport } from './routes/en.legal.terms'
import { Route as RuLegalOfferRouteImport } from './routes/ru.legal.offer'
import { Route as RuLegalPrivacyRouteImport } from './routes/ru.legal.privacy'
import { Route as RuLegalTermsRouteImport } from './routes/ru.legal.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShowsRoute = AuthenticatedAdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const EnLegalOfferRoute = EnLegalOfferRouteImport.update({
  id: '/legal/offer',
  path: '/legal/offer',
  getParentRoute: () => EnRoute,
} as any)
const EnLegalPrivacyRoute = EnLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnLegalTermsRoute = EnLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => EnRoute,
} as any)
const RuLegalOfferRoute = RuLegalOfferRouteImport.update({
  id: '/ru/legal/offer',
  path: '/ru/legal/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLegalPrivacyRoute = RuLegalPrivacyRouteImport.update({
  id: '/ru/legal/privacy',
  path: '/ru/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLegalTermsRoute = RuLegalTermsRouteImport.update({
  id: '/ru/legal/terms',
  path: '/ru/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/en': typeof EnIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/en/legal/offer': typeof EnLegalOfferRoute
  '/en/legal/privacy': typeof EnLegalPrivacyRoute
  '/en/legal/terms': typeof EnLegalTermsRoute
  '/ru/legal/offer': typeof RuLegalOfferRoute
  '/ru/legal/privacy': typeof RuLegalPrivacyRoute
  '/ru/legal/terms': typeof RuLegalTermsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/en/'
    | '/admin/enquiries'
    | '/admin/finance'
    | '/admin/shows'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/en'
    | '/admin/enquiries'
    | '/admin/finance'
    | '/admin/shows'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/en/'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/shows'
    | '/en/legal/offer'
    | '/en/legal/privacy'
    | '/en/legal/terms'
    | '/ru/legal/offer'
    | '/ru/legal/privacy'
    | '/ru/legal/terms'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnIndexRoute: typeof EnIndexRoute
  RuLegalOfferRoute: typeof RuLegalOfferRoute
  RuLegalPrivacyRoute: typeof RuLegalPrivacyRoute
  RuLegalTermsRoute: typeof RuLegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shows': {
      id: '/_authenticated/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AuthenticatedAdminShowsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/en/legal/offer': {
      id: '/en/legal/offer'
      path: '/legal/offer'
      fullPath: '/en/legal/offer'
      preLoaderRoute: typeof EnLegalOfferRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/legal/privacy': {
      id: '/en/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/en/legal/privacy'
      preLoaderRoute: typeof EnLegalPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/legal/terms': {
      id: '/en/legal/terms'
      path: '/legal/terms'
      fullPath: '/en/legal/terms'
      preLoaderRoute: typeof EnLegalTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/ru/legal/offer': {
      id: '/ru/legal/offer'
      path: '/ru/legal/offer'
      fullPath: '/ru/legal/offer'
      preLoaderRoute: typeof RuLegalOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/legal/privacy': {
      id: '/ru/legal/privacy'
      path: '/ru/legal/privacy'
      fullPath: '/ru/legal/privacy'
      preLoaderRoute: typeof RuLegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/legal/terms': {
      id: '/ru/legal/terms'
      path: '/ru/legal/terms'
      fullPath: '/ru/legal/terms'
      preLoaderRoute: typeof RuLegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminShowsRoute: typeof AuthenticatedAdminShowsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminShowsRoute: AuthenticatedAdminShowsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EnIndexRoute: EnIndexRoute,
  RuLegalOfferRoute: RuLegalOfferRoute,
  RuLegalPrivacyRoute: RuLegalPrivacyRoute,
  RuLegalTermsRoute: RuLegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
